# ====================================
# TMS Smart Setup configuration file
# Modify settings as needed.
# ====================================
# yaml-language-server: $schema=https://raw.githubusercontent.com/tmssoftware/smartsetup/refs/heads/main/tms/example-config/tms.config.schema.json


# General options that are not 'per product'.
tms smart setup options:

  # folder where smart setup will store the products along with its metadata, like downloaded files, unzipped files, logs, etc.
  # if empty (the default), all folders will be created where this tms.config.yaml file is located.
  # this folder can be located in a different disk than this configuration file.
  working folder: build

# Global configuration
configuration for all products:

  # general options for the product.
  options:
    # if true the components will be compiled but not registered in the IDE.
    # Also the Windows PATH won't be modified when this setting is true.
    # You can use "true" or "false" here to skip all or none, and also an array like "[All, Packages, StartMenu, Help, WindowsPath, WebCore, Registry, FileLinks]" to be more specific about what you want to skip.
    # For example: skip register: [StartMenu, Help] would skip registering the start menu and the help, but not the others.
    # When specifically skipping parts, you might want to use negatives, like [All, -StartMenu, -Help] to skip all but start menu and help.
    skip register: true

  # Compilation options for the product.
  compilation options:

    # Whether to build debug DCUs. Debug DCUs are useful for stepping into the component code, but they take more time to compile and double the used disk space.
    debug dcus: false

    # Packages can have pre/post build events, which can be a security risk, so we disable them by default.
    # If you need to enable them for some project, create a `configuration for project` section and enable them for that project.
    run build events: false

    # List of compiler defines to use for compiling. The defines here are added to the ones already defined before. To remove a define that is normally defined, set it to false, like for example " - DEBUG: false".
    defines:
      #- RTTI
      #- USE_UNICODE
